# Варіант 9

In [1]:
import numpy as np
import random

## Завдання 1
- з використанням універсальних функцій бібліотеки NumPy.
- за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
- для обох випадків підрахувати час виконання скрипту та
зробити висновки.

1, 2, 4, 7, 8, 12, 15, 16, 20

### Вправа 1. 
Вводиться число $n$. Вивести масив розміру $n×n$, в 
якому по діагоналі йдуть числавід 1 до $n$, а інші числа дорівнюють 0..

In [2]:
def task_1a(n):
    arr = np.arange(1, n + 1)
    return np.diag(arr)


def task_1b(n):
    arr = []

    for i in range(n):
        arr.append([0]*n)

    for i in range(n):
        arr[i][i] = i + 1

    return arr

In [3]:
n = int(input("Enter n: "))

res = task_1a(n)
print(res)

res = task_1b(n)
print(res)

Enter n:  4


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4]]


In [4]:
%%timeit -n 1000 -r 10

n = 100

task_1a(n)

6.36 µs ± 2.42 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [5]:
%%timeit -n 1000 -r 10

n = 100

task_1b(n)

47.5 µs ± 4.88 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 2.
Вводиться число $n$. Розставити 1 та 0 у шаховому 
порядку, починаючи з 1 в матриці розміром$ n×$n, використовуюи 
слайсінг.

In [6]:
def task_2a(n):
    board = np.zeros((n, n), dtype=int)
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1
    
    return board


def task_2b(n):
    board = []
    
    for i in range(n):
        row = []
        
        for j in range(n):
          if (i + j) % 2 == 0:
            row.append(1)
          else:
            row.append(0)
        
        board.append(row)
      
    return board

In [7]:
n = int(input("Enter n: "))

res = task_2a(n)
print(res)

res = task_2b(n)
print(res)

Enter n:  4


[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]
[[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]]


In [8]:
%%timeit -n 1000 -r 10

n = 100

task_2a(n)

6.97 µs ± 1.35 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [9]:
%%timeit -n 1000 -r 10

n = 100

task_2b(n)

902 µs ± 25.9 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 4.
Вводяться числа $n$ і $m$. Вивести масив розміру $n×m$, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до $m–1$, а всі інші елементи матриці дорівнюють 0.

In [10]:
def task_4a(n, m):
    arr = np.zeros((n, m), dtype=int)
    arr[0] = np.arange(m)

    return arr


def task_4b(n, m):
    arr = []

    for i in range(n):
        if i == 0:
            arr.append(list(range(m)))
        else:
            arr.append([0]*m)
    
    return arr

In [11]:
n = int(input("Enter n: "))
m = int(input("Enter m: "))

res = task_4a(n, m)
print(res)

res = task_4b(n, m)
print(res)

Enter n:  3
Enter m:  4


[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
[[0, 1, 2, 3], [0, 0, 0, 0], [0, 0, 0, 0]]


In [12]:
%%timeit -n 1000 -r 10

n = 50
m = 100

task_4a(n, m)

3.1 µs ± 648 ns per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [13]:
%%timeit -n 1000 -r 10

n = 50
m = 100

task_4b(n, m)

20.2 µs ± 2.44 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 7.
З клавіатури вводиться масив. Замінити всі нульові елементи на –1..

In [14]:
def task_7a(arr):
    np_arr = np.array(arr)
    np_arr[np_arr == 0] = -1

    return np_arr


def task_7b(arr):
    return [elem if elem != 0 else -1 for elem in arr]

In [15]:
str_arr = input("Enter an array: ").split()
arr = list(map(int, str_arr))

res = task_7a(arr)
print(res)

res = task_7b(arr)
print(res)

Enter an array:  3 4 0 9 7 0 6 0 4 0 3


[ 3  4 -1  9  7 -1  6 -1  4 -1  3]
[3, 4, -1, 9, 7, -1, 6, -1, 4, -1, 3]


In [16]:
%%timeit -n 1000 -r 10

arr = [3, 4, 0, 6, 5, 0, 3, 0, 4]

task_7a(arr)

3.23 µs ± 433 ns per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [17]:
%%timeit -n 1000 -r 10

arr = [3, 4, 0, 6, 5, 0, 3, 0, 4]

task_7b(arr)

1.18 µs ± 330 ns per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 8.
З клавіатури вводиться масив. Підрахувати в ньому 
кількість нульових та ненульових елементів.

In [18]:
def task_8a(arr):
    nonzero_count = np.count_nonzero(arr)
    zero_cout = len(arr) - nonzero_count

    return nonzero_count, zero_cout


def task_8b(arr):
    nonzero_count = sum(1 for elem in arr if elem != 0)
    zero_cout = len(arr) - nonzero_count

    return nonzero_count, zero_cout

In [19]:
str_arr = input("Enter an array: ").split()
arr = list(map(int, str_arr))

counts = task_8a(arr)
print(f"Non zeros: {counts[0]}")
print(f"Zeros: {counts[1]}")

counts = task_8b(arr)
print(f"Non zeros: {counts[0]}")
print(f"Zeros: {counts[1]}")

Enter an array:  3 4 0 9 7 0 6 0 4 0 3


Non zeros: 7
Zeros: 4
Non zeros: 7
Zeros: 4


In [20]:
%%timeit -n 1000 -r 10

arr = [3, 4, 0, 6, 5, 0, 3, 0, 4]

task_8a(arr)

2.8 µs ± 470 ns per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [21]:
%%timeit -n 1000 -r 10

arr = [3, 4, 0, 6, 5, 0, 3, 0, 4]

task_8b(arr)

1.02 µs ± 178 ns per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 12.
Створити масив одиниць розміром $n×n$ та створити в 
ньому «рамку», що утворюється з 0.

In [22]:
def task_12a(n):
    ones = np.ones((n, n), dtype=int)
    ones[::n-1] = 0
    ones[::, ::n-1] = 0

    return ones


def task_12b(n):
    ones = []

    for i in range(n):
        if i == 0 or i == n-1:
            ones.append([0]*n)
        else:
            row = [1]*n
            row[0] = 0
            row[-1] = 0
            ones.append(row)

    return ones

In [23]:
n = int(input("Enter n: "))

res = task_12a(n)
print(res)

res = task_12b(n)
print(res)

Enter n:  4


[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
[[0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]


In [24]:
%%timeit -n 1000 -r 10

n = 100

task_12a(n)

6.05 µs ± 2.3 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [25]:
%%timeit -n 1000 -r 10

n = 100

task_12b(n)

44.4 µs ± 2.15 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 15.
Заповнити парні стовпчикі матриці розміром $n×n$ 
одиницями, а непарні – нулями.

In [26]:
def task_15a(n):
    cage = np.zeros((n, n), dtype=int)
    cage[::, 1::2] = 1

    return cage


def task_15b(n):
    cage = []
    
    for i in range(n):
        cage.append([elem % 2 for elem in range(n)])
        
    return cage

In [27]:
n = int(input("Enter n: "))

res = task_15a(n)
print(res)

res = task_15b(n)
print(res)

Enter n:  4


[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[0, 1, 0, 1], [0, 1, 0, 1], [0, 1, 0, 1], [0, 1, 0, 1]]


In [28]:
%%timeit -n 1000 -r 10

n = 100

task_15a(n)

5.48 µs ± 1e+03 ns per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [29]:
%%timeit -n 1000 -r 10

n = 100

task_15b(n)

433 µs ± 10.4 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 16. 
Заповнити вектор значеннями від 0 до $n$. Всі значення, що більші за $(\frac{n}{4})$ та менші за $(\frac{3n}{4})$ замінити нулями..

In [30]:
def task_16a(n):
    arr = np.arange(n + 1)
    arr[(n/4 < arr) & (arr < 3*n/4)] = 0
    
    return arr


def task_16b(n):
    return [0 if (n/4 < elem and elem < 3*n/4) else elem for elem in range(n + 1)]

In [31]:
n = int(input("Enter n: "))

res = task_16a(n)
print(res)

res = task_16b(n)
print(res)

Enter n:  4


[0 1 0 3 4]
[0, 1, 0, 3, 4]


In [32]:
%%timeit -n 1000 -r 10

n = 100

task_16a(n)

6.43 µs ± 1.28 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [33]:
%%timeit -n 1000 -r 10

n = 100

task_16b(n)

16 µs ± 1.45 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


### Вправа 20.
Згенерувати вектор із $n$ випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [34]:
def task_20a(n):
    arr = np.random.random(n)

    #print(f"Initial array: {arr}")
    index = np.argmax(arr)
    arr[index] = 0
    
    #print(f"Permutated array: {arr}")

    return arr


def task_20b(n):
    arr = [random.random() for _ in range(n)]

    #print(f"Initial array: {arr}")
    max_value = max(arr)
    index = arr.index(max_value)
    arr[index] = 0
    
    #print(f"Permutated array: {arr}")

    return arr

In [35]:
n = int(input("Enter n: "))

res = task_20a(n)
print(res)

res = task_20b(n)
print(res)

Enter n:  4


[0.18960585 0.         0.04745223 0.01930974]
[0.06814077695302545, 0, 0.5187997596614172, 0.014736100155862686]


In [36]:
%%timeit -n 1000 -r 10

n = 100

task_20a(n)

5.07 µs ± 920 ns per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [37]:
%%timeit -n 1000 -r 10

n = 100

task_20b(n)

12.6 µs ± 2.45 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


## Завдання 2
Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку за допомогою:
- матричного множення;
- оберненої матриці;
- функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose().

In [38]:
a = [
    [1, 2, 1, 1],
    [2, 1, 1, 1],
    [1, -1, 2, 1],
    [1, 1, -1, 3]
]

b = [8, 5, -1, 10]


def my_solution():
    res = []
    n = len(b)
    main_det = np.linalg.det(a)

    if main_det == 0:
        print("Determinant cannot be 0")
        return []
    
    for i in range(n):
        sub_matrix = replace_column(a, b, i)
        sub_det = np.linalg.det(sub_matrix)
        
        res.append(sub_det / main_det)

    return res


def replace_column(matrix, row, index):
    res = np.array(matrix)

    for i in range(len(row)):
        res[i][index] = row[i]

    return res

In [39]:
def check_a():
  a_inv = np.linalg.inv(a)
  b_inv = np.array(b).reshape(-1, 1)

  return np.dot(a_inv, b_inv)

def check_b():
  return np.linalg.solve(a, b)

In [40]:
res_my = my_solution()
print(res_my)

res_a = check_a()
print(res_a)

res_b = check_b()
print(res_b)


print(np.allclose(res_my, res_a.reshape(1, len(b))))
print(np.allclose(res_my, res_b))
print(np.allclose(res_b,  res_a.reshape(1, len(b))))

[-0.05263157894736862, 2.9473684210526305, -0.1578947368421053, 2.3157894736842115]
[[-0.05263158]
 [ 2.94736842]
 [-0.15789474]
 [ 2.31578947]]
[-0.05263158  2.94736842 -0.15789474  2.31578947]
True
True
True


## Завдання 3

Обчислити значення матричного виразу:
- з використанням універсальних функцій бібліотеки NumPy.
- за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
- для обох випадків підрахувати час виконання скрипту та зробити висновок.

Порівняти всі рішення за допомогою функції numpy.allclose().

In [41]:
A = np.array([
    [1, 4, 2],
    [2, 1, -2],
    [0, 1, -1]
])

B = np.array([
    [4, 6, -2],
    [4, 10, 1],
    [2, 4, -5]
])

def solution_a():
    return 2 * A - (A@A + B) @ B


def solution_b():
    term1 = scalar_product(2, A)
    
    term2 = matrix_product(A, A)
    term3 = matrix_sum(term2, B)

    term4 = matrix_product(term3, B)
    term5 = scalar_product(-1, term4)
    
    return matrix_sum(term1, term5)
    

def matrix_sum(a_matrix, b_matrix):
    res = []
    n = len(a_matrix[0])

    for i in range(n):
        row = []
        
        for j in range(n):
            row.append(a_matrix[i][j] + b_matrix[i][j])
        res.append(row)

    return res


def scalar_product(scalar, matrix):
    res = []
    n = len(matrix[0])
    
    for i in range(n):
        res.append([scalar * elem for elem in matrix[i]])

    return res


def matrix_product(a_matrix, b_matrix):
    res = []
    
    for i in range(len(a_matrix)):
        row = []
      
        for j in range(len(b_matrix[0])):
            element = sum(a_matrix[i][k] * b_matrix[k][j] for k in range(len(a_matrix[0])))
            row.append(element)
        
        res.append(row)

    return res

In [42]:
res_a = solution_a()
print(res_a)

res_b = solution_b()
print(res_b)

print(np.allclose(res_a, res_b))

[[ -94 -190  -36]
 [-106 -236   20]
 [ -20  -38  -28]]
[[-94, -190, -36], [-106, -236, 20], [-20, -38, -28]]
True


In [43]:
%%timeit -n 1000 -r 10

solution_a()

6.12 µs ± 1.7 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)


In [44]:
%%timeit -n 1000 -r 10

solution_b()

54.8 µs ± 2.7 µs per loop (mean ± std. dev. of 10 runs, 1,000 loops each)
